### ISSUE TITLE
Не работает в Firefox 70.0

### ISSUE THREAD

**Issue by abitrolly** [ushchent/el_machina#2]
http://ushchent.github.io/el_machina/ в лисе выглядит так.

![image](https://user-images.githubusercontent.com/8781107/68649460-d6985580-0533-11ea-8948-7dc354424180.png)

И ничего не кликабельно. Есть вероятность, что я смогу самостоятельно разобраться и запустить эту штуку, но сегодня возможно времени не будет.

**Comment by Semigradsky** [comment]
Firefox 70.0.1, Windows 10 - работает нормально.

Возможно как-то связано с предупреждением, которое появляется в Chrome:

![image](https://user-images.githubusercontent.com/1198848/68662217-76aea880-054d-11ea-9bf4-cd8cd0178db0.png)

**Comment by abitrolly** [comment]
Алексей обновил данные - https://github.com/ushchent/el_machina/commits/2a6e015606c33c9843d1a97a26914ee80120f12f и сайт заработал. Табличка показывается.

Но всё равно странно. Такое ощущение, что она показывает всех кандидатов, а не только избранных.

![image](https://user-images.githubusercontent.com/8781107/68686170-45010600-057c-11ea-9c86-35614ad89480.png)
