### ISSUE TITLE
Результаты предсказания

### ISSUE THREAD

**Issue by abitrolly** [ushchent/el_machina#3]
@ushchent а результат предсказания, собсна, есть? http://ushchent.github.io/el_machina/ выводит таблицу всех кандидатов, и фильтров нет никаких.

**Comment by ushchent** [comment]
Как раз добавил колонку. В посковой строчке можно указать "Проходит", и покажутся все счастливчики.

**Comment by abitrolly** [comment]
В `window.location.search` можно передать параметр для поиска через URL http://ushchent.github.io/el_machina/?Проходит но я пока не вижу где сама форма инициализируется.

**Comment by abitrolly** [comment]
А что используется для предсказания?

**Comment by ushchent** [comment]
Каждый по-своему. Я использую scikit-learn.

**Comment by abitrolly** [comment]
Завтра в 18 в Малиновом хакерспейсе буду пробовать что-нибудь предсказать на `mindsdb`. Не знаю, получится или нет. Она всё-таки на числовые параметры больше заточена по докам.
